# Generated by Django 3.1.4 on 2021-04-28 07:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('uphone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[6-9]\\d{9}$')])),
                ('uemail', models.EmailField(max_length=50)),
                ('utable', models.CharField(choices=[('single', 'Single/Couple Table (1 to 2 Members)'), ('small', 'Small Family Table (2 to 4 Members)'), ('mini', 'Mini-Joint Family Table (4-6 Members)'), ('jointf', 'Joint Family Table (6-12 Members)')], max_length=50)),
                ('uarrtime', models.CharField(choices=[('1', '7:00PM'), ('2', '7:30 PM'), ('3', '8:00PM'), ('4', '8:30PM'), ('5', '9:00PM'), ('6', '9:30PM'), ('7', '10:00PM'), ('8', '10:30 PM'), ('9', '11:00 PM')], max_length=50)),
                ('umsg', models.TextField(default='No Messages', max_length=500)),
                ('CheckIn', models.BooleanField(default=False)),
                ('CheckOut', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_st', models.DateTimeField(auto_now=True)),
                ('otp', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
