# Generated by Django 3.1.4 on 2021-04-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munchin', '0003_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(upload_to='munchin/static/FoodItem/'),
        ),
    ]
