# Generated by Django 3.1.4 on 2021-04-29 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('munchin', '0008_auto_20210429_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Foodorder',
        ),
    ]
