# Generated by Django 3.1.4 on 2021-04-30 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munchin', '0011_auto_20210501_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
